### PR TITLE
Added more charts and info for the stats page

### PR DESCRIPTION
**Pull request by okb1100**
It is incomplete and needs some UI work but better than just a map. ☺️

### CODE REVIEW

**Comment by cagataycali** [comment]
Ah, thanks for your contribution!
Is there any screenshots for these?

**Comment by okb1100** [comment]
stats
Here it is running locally.

**Comment by cagataycali** [comment]
That looks awesome, If you activate the map, I want to merge the code.

**Comment by okb1100** [comment]
I think the map issue is related to `country` and `ip` variables are being `null` when the proejct is run locally. I am now going to test it on an actual server and inform you.

**Comment by cagataycali** [comment]
You are right. Brillant solution. I'm merging.

**Comment by cagataycali** [comment]
That's alive now. Thanks for cool google charts addition. @okb1100

**Comment by okb1100** [comment]
You are most welcome :)

**Pull request merged**
